### render.yaml
```yaml
services:
  - type: web
    name: banking-apk-detector
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
